services:
  kontora-server:
    depends_on:
      - postgres
    container_name: kontora-server
    build:
      context: .
      dockerfile: Dockerfile
    image: kontora-server:latest
    ports:
      - "8082:8082"
  postgres:
    container_name: postgres
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres:
